version: 2
updates:
  # اکشن‌های ورک‌فلوها
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
    labels:
      - dependencies

  # اگر روزی پکیجی اضافه شد، به‌روزرسانی‌های ریز یک‌جا بیایند
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
